 web:
     image: nginx:latest
     container_name: sn_web
     ports:
         - "80:80"
     volumes:
         - ./apps:/apps
         - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
     links:
         - php
 php:
     build: .
     container_name: sn_php
     volumes:
         - ./apps:/apps